import {writeFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const IA='https://archive.org/advancedsearch.php',IMG=id=>`https://archive.org/services/img/${encodeURIComponent(id)}`,C='https://commons.wikimedia.org/w/api.php',ROWS=200;
const MOV='Category:Videos of films in the public domain',SER=['Category:Videos of The Beverly Hillbillies'];
const X=/\b(trailer|teaser|preview|promo|clip|excerpt|segment|commercial|advertisement)\b|трейл|тийзър|реклама|откъс/i;
const G=[['Екшън',/\b(action|martial arts|war film)\b/i],['Приключенски',/\badventure\b/i],['Анимация',/\b(animation|animated|cartoon)\b/i],['Комедия',/\b(comedy|comedies)\b/i],['Криминален',/\b(crime|detective|gangster)\b/i],['Документален',/\b(documentary|nonfiction)\b/i],['Драма',/\b(drama|melodrama)\b/i],['Фентъзи',/\bfantasy\b/i],['Ужаси',/\bhorror\b/i],['Мюзикъл',/\bmusical\b/i],['Романтичен',/\b(romance|romantic)\b/i],['Фантастика',/\b(science fiction|sci[- ]?fi)\b/i],['Трилър',/\b(thriller|suspense)\b/i],['Уестърн',/\b(western)\b/i]];
const K=[['САЩ',/\b(united states|u\.s\.a\.?|usa|american film)\b/i],['Великобритания',/\b(united kingdom|british|england)\b/i],['Франция',/\b(france|french)\b/i],['Германия',/\b(germany|german)\b/i],['Италия',/\b(italy|italian)\b/i],['Испания',/\b(spain|spanish)\b/i],['Русия',/\b(russia|russian|soviet union|ussr|soviet film)\b/i],['Иран',/\b(iran|iranian|persian film)\b/i],['Индия',/\b(india|indian film|bollywood)\b/i],['Япония',/\b(japan|japanese film)\b/i],['Китай',/\b(china|chinese film)\b/i],['Канада',/\b(canada|canadian film)\b/i],['Австралия',/\b(australia|australian film)\b/i],['България',/\b(bulgaria|bulgarian film)\b|българ/i]];
const a=v=>Array.isArray(v)?v:(v?[v]:[]),t=v=>a(v).join(' · '),strip=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim(),pool=(...p)=>p.flatMap(a).map(strip).join(' · '),yr=v=>String(v||'').match(/\b(18|19|20)\d{2}\b/)?.[0]||'',sec=v=>{if(v==null)return 0;if(typeof v==='number')return v;let s=String(v).trim();if(/^\d+(\.\d+)?$/.test(s))return +s;let p=s.split(':').map(Number);return p.some(Number.isNaN)?0:p.reduce((q,n)=>q*60+n,0)},pick=(s,A,d)=>A.find(x=>x[1].test(s))?.[0]||d,gv=(o,k)=>strip(o?.[k]?.value||'');
async function j(u){let r=await fetch(u,{headers:{'user-agent':'All-World-Cinema-Catalog/4.0'}});if(!r.ok)throw Error(`${r.status} ${u}`);return r.json()}
function iu(type,page){let col=type==='movie'?'feature_films':'classic_tv',p=new URLSearchParams({q:`mediatype:movies AND collection:${col}`,rows:String(ROWS),page:String(page),output:'json',sort:'downloads desc'});['identifier','title','date','year','subject','description','creator','language','collection','coverage','runtime','duration'].forEach(f=>p.append('fl[]',f));return `${IA}?${p}`}
function li(d,type){let title=t(d.title);if(!d?.identifier||!title||X.test(title))return null;let duration=sec(d.runtime||d.duration);if(type==='movie'&&duration&&duration<2400||type==='series'&&duration&&duration<900)return null;let p=pool(d.subject,d.description,d.creator,d.language,d.coverage,d.collection);return{key:`ia:${d.identifier}`,source:'ia',type,identifier:d.identifier,title,year:yr(d.date||d.year||title),genre:pick(p,G,'Друг'),country:pick(p,K,'Неизвестна'),duration,poster:IMG(d.identifier),detailPending:true}}
async function iai(type){let f=await j(iu(type,1)),n=+f?.response?.numFound||0,pages=Math.max(1,Math.ceil(n/ROWS)),out=(f?.response?.docs||[]).map(x=>li(x,type)).filter(Boolean);console.log(`[IA ${type}] 1/${pages}`);for(let p=2;p<=pages;p++){let d=await j(iu(type,p));out.push(...(d?.response?.docs||[]).map(x=>li(x,type)).filter(Boolean));console.log(`[IA ${type}] ${p}/${pages}`)}return out}
function cu(cat,cont={}){let p=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'categorymembers',gcmtitle:cat,gcmtype:'file',gcmlimit:'500',prop:'videoinfo',viprop:'url|timedtext|extmetadata|commonmetadata',viurlwidth:'240',viextmetadatalanguage:'en'});Object.entries(cont).forEach(([k,v])=>p.set(k,v));return `${C}?${p}`}
function lc(page,type,cat){let title=String(page.title||'').replace(/^File:/i,'').replace(/\.(webm|ogv|ogg|mp4)$/i,'').replace(/_/g,' ').trim();if(!title||X.test(title))return null;let vi=page.videoinfo?.[0];if(!vi)return null;let cm=vi.commonmetadata||{},ex=vi.extmetadata||{},duration=sec(cm.duration||cm.Duration||gv(ex,'Duration'));if(type==='movie'&&duration&&duration<2400||type==='series'&&duration&&duration<900)return null;let desc=gv(ex,'ImageDescription')||gv(ex,'ObjectName'),p=pool(title,desc,gv(ex,'Categories'),gv(ex,'Credit'),gv(ex,'DateTimeOriginal'),cat);return{key:`commons:${page.pageid}`,source:'commons',type,pageid:page.pageid,pageTitle:page.title,category:cat,title,year:yr(gv(ex,'DateTimeOriginal')||title),genre:pick(p,G,'Друг'),country:pick(p,K,'Неизвестна'),duration,poster:vi.thumburl||'',detailPending:false}}
async function ci(type){let cats=type==='movie'?[MOV]:SER,out=[];for(let cat of cats){let c={},n=0;do{let d=await j(cu(cat,c));n++;Object.values(d?.query?.pages||{}).forEach(p=>{let x=lc(p,type,cat);if(x)out.push(x)});c=d?.continue||null;console.log(`[Commons ${type}] ${cat} ${n}`)}while(c)}return out}
function dd(items){let m=new Map;for(let x of items){let k=x.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()+`|${x.year||''}`,p=m.get(k);if(!p)m.set(k,x);else{let s=o=>(o.duration?2:0)+(o.poster?1:0)+(o.source==='commons'?1:0);if(s(x)>s(p))m.set(k,x)}}return[...m.values()].sort((a,b)=>(+b.year||0)-(+a.year||0)||a.title.localeCompare(b.title))}
let [im,is,cm,cs]=await Promise.all([iai('movie'),iai('series'),ci('movie'),ci('series')]),movie=dd([...im,...cm]),series=dd([...is,...cs]),out={version:4,generatedAt:new Date().toISOString(),counts:{movie:movie.length,series:series.length,total:movie.length+series.length},movie,series},here=dirname(fileURLToPath(import.meta.url)),target=resolve(here,'..','catalog.json');await writeFile(target,JSON.stringify(out,null,2)+'\n');console.log(`Wrote ${movie.length} movies + ${series.length} series episodes`);