export const LANGUAGES=[
['bg','Български'],['en','English'],['de','Deutsch'],['fr','Français'],['es','Español'],['it','Italiano'],['pt','Português'],
['ro','Română'],['el','Ελληνικά'],['tr','Türkçe'],['pl','Polski'],['cs','Čeština'],['uk','Українська'],['ru','Русский']
];
const EN={
title:'Online radio',local:'Local',world:'World',favorites:'Favorites',recent:'Recently played',
country:'Country',currentCountry:'Current country',genre:'Genre',cancel:'Cancel',save:'Save',
search:'Search stations…',localHeading:'Local stations',worldHeading:'World stations',favoritesHeading:'Favorite stations',recentHeading:'Recently played',
localDesc:'Stations from your current country: {country}',worldDesc:'Stations from around the world',favoritesDesc:'Favorites stored locally',recentDesc:'Your recently played stations',
allCountries:'All countries',loading:'Loading…',catalogLoadingText:'Connecting to the radio catalog…',catalogOnline:'Catalog online',catalogCache:'Local cache',catalogError:'Catalog unavailable',catalogCount:'Catalog: {count} stations',
noStations:'No stations found',noStationsText:'Change genre or search and try again.',ready:'Ready',chooseStation:'Choose a radio station',connecting:'Connecting…',playing:'Playing',paused:'Paused',stopped:'Stopped',streamError:'The stream could not be played',
offline:'Offline',online:'Online',sleepTimer:'Sleep timer',off:'Off',favoriteAdded:'Added to Favorites.',favoriteRemoved:'Removed from Favorites.',
addToFavorites:'Add to favorites',inFavorites:'In favorites',refresh:'Refresh',advertising:'Advertising space',play:'Play',stop:'Stop',install:'Install',privacySettings:'Privacy settings',testAdsBadge:'TEST ADS · no real revenue',webConsentTestNote:'This is a development test-consent interface. A production Web CMP is not configured yet.',allowTestAds:'Allow test ads',limitTestAds:'Limit test ads',close:'Close',rightsTestOpen:'Playback enabled (local test)',rightsPublicStream:'Public HTTPS stream',aboutRightsPublicDirectNote:'PUBLIC HTTPS DIRECT MODE: the player connects from the browser directly to public HTTPS station streams after technical sandbox checks. This does not claim embedding or commercial-use rights; station terms and rights still require review.',aboutRightsLocalTestNote:'LOCAL TEST MODE: all catalog stations with a public HTTPS stream may be played after the network sandbox check. This is not evidence of embedding or commercial-use rights. Production remains on the strict Rights Gate.'
};
const full=o=>({...EN,...o});
export const TRANSLATIONS={
en:EN,
bg:full({
title:'Онлайн радио',local:'Местни',world:'Световни',favorites:'Любими',recent:'Последно слушани',country:'Държава',currentCountry:'Текуща държава',genre:'Жанр',cancel:'Отказ',save:'Запиши',search:'Търси станция…',localHeading:'Местни станции',worldHeading:'Световни станции',favoritesHeading:'Любими станции',recentHeading:'Последно слушани',localDesc:'Радиостанции от текущата държава: {country}',worldDesc:'Станции от целия свят',favoritesDesc:'Запазени локално любими станции',recentDesc:'Последните слушани станции',allCountries:'Всички държави',loading:'Зареждане…',catalogLoadingText:'Свързване с радио каталога…',catalogOnline:'Каталог онлайн',catalogCache:'Локален кеш',catalogError:'Няма връзка с каталога',catalogCount:'Каталог: {count} радиостанции',noStations:'Няма намерени станции',noStationsText:'Промени жанра или търсенето и опитай отново.',ready:'Готово',chooseStation:'Избери радиостанция',connecting:'Свързване…',playing:'Възпроизвежда се',paused:'На пауза',stopped:'Спряно',streamError:'Потокът не може да се възпроизведе',offline:'Офлайн',online:'Онлайн',sleepTimer:'Таймер за заспиване',off:'Изкл.',favoriteAdded:'Добавено в Любими.',favoriteRemoved:'Премахнато от Любими.',addToFavorites:'Добави в любими',inFavorites:'В любими',refresh:'Обнови',advertising:'Рекламно пространство',play:'Пусни',stop:'Спри',install:'Инсталирай',privacySettings:'Настройки за поверителност',testAdsBadge:'TEST ADS · без реални приходи',webConsentTestNote:'Това е тестов consent интерфейс за разработка. Production Web CMP още не е конфигуриран.',allowTestAds:'Разреши тестови реклами',limitTestAds:'Ограничи тестовите реклами',close:'Затвори',rightsTestOpen:'Възпроизвеждането е разрешено (локален тест)',rightsPublicStream:'Публичен HTTPS поток',aboutRightsPublicDirectNote:'РЕЖИМ PUBLIC HTTPS DIRECT: плейърът се свързва директно от браузъра към публичния HTTPS поток след техническа sandbox проверка. Това не е твърдение за права за вграждане или търговска употреба; условията и правата на станцията остават за проверка.',aboutRightsLocalTestNote:'ЛОКАЛЕН ТЕСТОВ РЕЖИМ: всички станции от каталога с публичен HTTPS поток могат да се възпроизвеждат след мрежова sandbox проверка. Това не е доказателство за права за вграждане или търговска употреба. Production режимът остава със строг Rights Gate.'
}),
de:full({title:'Online-Radio',local:'Lokal',world:'Weltweit',favorites:'Favoriten',recent:'Zuletzt gehört',country:'Land',currentCountry:'Aktuelles Land',genre:'Genre',cancel:'Abbrechen',save:'Speichern',search:'Sender suchen…',localHeading:'Lokale Sender',worldHeading:'Sender weltweit',favoritesHeading:'Favoriten',recentHeading:'Zuletzt gehört',localDesc:'Sender aus deinem aktuellen Land: {country}',worldDesc:'Sender aus aller Welt',favoritesDesc:'Lokal gespeicherte Favoriten',recentDesc:'Zuletzt gehörte Sender',allCountries:'Alle Länder',loading:'Laden…',catalogOnline:'Katalog online',catalogCache:'Lokaler Cache',catalogError:'Katalog nicht verfügbar',catalogCount:'Katalog: {count} Sender',noStations:'Keine Sender gefunden',noStationsText:'Ändere Genre oder Suche und versuche es erneut.',ready:'Bereit',chooseStation:'Radiosender auswählen',connecting:'Verbinden…',playing:'Wiedergabe',paused:'Pausiert',stopped:'Gestoppt',streamError:'Der Stream konnte nicht abgespielt werden',offline:'Offline',online:'Online',sleepTimer:'Sleep-Timer',off:'Aus',favoriteAdded:'Zu Favoriten hinzugefügt.',favoriteRemoved:'Aus Favoriten entfernt.',addToFavorites:'Zu Favoriten',inFavorites:'In Favoriten',refresh:'Aktualisieren',advertising:'Werbefläche',play:'Abspielen',stop:'Stopp',install:'Installieren'}),
fr:full({title:'Radio en ligne',local:'Locales',world:'Monde',favorites:'Favoris',recent:'Écoutées récemment',country:'Pays',currentCountry:'Pays actuel',genre:'Genre',cancel:'Annuler',save:'Enregistrer',search:'Rechercher une station…',localHeading:'Stations locales',worldHeading:'Stations du monde',favoritesHeading:'Stations favorites',recentHeading:'Écoutées récemment',localDesc:'Stations de votre pays actuel : {country}',worldDesc:'Stations du monde entier',favoritesDesc:'Favoris enregistrés localement',recentDesc:'Vos dernières stations écoutées',allCountries:'Tous les pays',loading:'Chargement…',catalogOnline:'Catalogue en ligne',catalogCache:'Cache local',catalogError:'Catalogue indisponible',catalogCount:'Catalogue : {count} stations',noStations:'Aucune station trouvée',noStationsText:'Modifiez le genre ou la recherche puis réessayez.',ready:'Prêt',chooseStation:'Choisissez une station de radio',connecting:'Connexion…',playing:'Lecture',paused:'En pause',stopped:'Arrêté',streamError:'Le flux ne peut pas être lu',offline:'Hors ligne',online:'En ligne',sleepTimer:'Minuteur de veille',off:'Désactivé',favoriteAdded:'Ajoutée aux favoris.',favoriteRemoved:'Retirée des favoris.',addToFavorites:'Ajouter aux favoris',inFavorites:'Dans les favoris',refresh:'Actualiser',advertising:'Espace publicitaire',play:'Lire',stop:'Arrêter',install:'Installer'}),
es:full({title:'Radio online',local:'Locales',world:'Mundo',favorites:'Favoritos',recent:'Escuchadas recientemente',country:'País',currentCountry:'País actual',genre:'Género',cancel:'Cancelar',save:'Guardar',search:'Buscar emisoras…',localHeading:'Emisoras locales',worldHeading:'Emisoras del mundo',favoritesHeading:'Emisoras favoritas',recentHeading:'Escuchadas recientemente',localDesc:'Emisoras de tu país actual: {country}',worldDesc:'Emisoras de todo el mundo',favoritesDesc:'Favoritos guardados localmente',recentDesc:'Tus últimas emisoras escuchadas',allCountries:'Todos los países',loading:'Cargando…',catalogOnline:'Catálogo online',catalogCache:'Caché local',catalogError:'Catálogo no disponible',catalogCount:'Catálogo: {count} emisoras',noStations:'No se encontraron emisoras',noStationsText:'Cambia el género o la búsqueda e inténtalo de nuevo.',ready:'Listo',chooseStation:'Elige una emisora de radio',connecting:'Conectando…',playing:'Reproduciendo',paused:'En pausa',stopped:'Detenido',streamError:'No se pudo reproducir el stream',offline:'Sin conexión',online:'En línea',sleepTimer:'Temporizador',off:'Desactivado',favoriteAdded:'Añadida a Favoritos.',favoriteRemoved:'Eliminada de Favoritos.',addToFavorites:'Añadir a favoritos',inFavorites:'En favoritos',refresh:'Actualizar',advertising:'Espacio publicitario',play:'Reproducir',stop:'Detener',install:'Instalar'}),
it:full({title:'Radio online',local:'Locali',world:'Mondo',favorites:'Preferiti',recent:'Ascoltate di recente',country:'Paese',currentCountry:'Paese attuale',genre:'Genere',cancel:'Annulla',save:'Salva',search:'Cerca stazioni…',localHeading:'Stazioni locali',worldHeading:'Stazioni dal mondo',favoritesHeading:'Stazioni preferite',recentHeading:'Ascoltate di recente',localDesc:'Stazioni del tuo paese attuale: {country}',worldDesc:'Stazioni da tutto il mondo',favoritesDesc:'Preferiti salvati localmente',recentDesc:'Le tue ultime stazioni ascoltate',allCountries:'Tutti i paesi',loading:'Caricamento…',catalogOnline:'Catalogo online',catalogCache:'Cache locale',catalogError:'Catalogo non disponibile',catalogCount:'Catalogo: {count} stazioni',noStations:'Nessuna stazione trovata',noStationsText:'Cambia genere o ricerca e riprova.',ready:'Pronto',chooseStation:'Scegli una stazione radio',connecting:'Connessione…',playing:'In riproduzione',paused:'In pausa',stopped:'Fermato',streamError:'Impossibile riprodurre lo stream',offline:'Offline',online:'Online',sleepTimer:'Timer spegnimento',off:'Disattivato',favoriteAdded:'Aggiunta ai Preferiti.',favoriteRemoved:'Rimossa dai Preferiti.',addToFavorites:'Aggiungi ai preferiti',inFavorites:'Nei preferiti',refresh:'Aggiorna',advertising:'Spazio pubblicitario',play:'Riproduci',stop:'Ferma',install:'Installa'}),
pt:full({title:'Rádio online',local:'Locais',world:'Mundo',favorites:'Favoritos',recent:'Ouvidas recentemente',country:'País',currentCountry:'País atual',genre:'Género',cancel:'Cancelar',save:'Guardar',search:'Pesquisar estações…',localHeading:'Estações locais',worldHeading:'Estações do mundo',favoritesHeading:'Estações favoritas',recentHeading:'Ouvidas recentemente',localDesc:'Estações do seu país atual: {country}',worldDesc:'Estações de todo o mundo',favoritesDesc:'Favoritos guardados localmente',recentDesc:'As suas últimas estações ouvidas',allCountries:'Todos os países',loading:'A carregar…',catalogOnline:'Catálogo online',catalogCache:'Cache local',catalogError:'Catálogo indisponível',catalogCount:'Catálogo: {count} estações',noStations:'Nenhuma estação encontrada',noStationsText:'Altere o género ou a pesquisa e tente novamente.',ready:'Pronto',chooseStation:'Escolha uma estação de rádio',connecting:'A ligar…',playing:'A reproduzir',paused:'Em pausa',stopped:'Parado',streamError:'Não foi possível reproduzir o stream',offline:'Offline',online:'Online',sleepTimer:'Temporizador',off:'Desligado',favoriteAdded:'Adicionada aos Favoritos.',favoriteRemoved:'Removida dos Favoritos.',addToFavorites:'Adicionar aos favoritos',inFavorites:'Nos favoritos',refresh:'Atualizar',advertising:'Espaço publicitário',play:'Reproduzir',stop:'Parar',install:'Instalar'}),
ro:full({title:'Radio online',local:'Locale',world:'Lume',favorites:'Favorite',recent:'Ascultate recent',country:'Țară',currentCountry:'Țara curentă',genre:'Gen',cancel:'Anulează',save:'Salvează',search:'Caută posturi…',localHeading:'Posturi locale',worldHeading:'Posturi din lume',favoritesHeading:'Posturi favorite',recentHeading:'Ascultate recent',localDesc:'Posturi din țara curentă: {country}',worldDesc:'Posturi din întreaga lume',favoritesDesc:'Favorite salvate local',recentDesc:'Ultimele posturi ascultate',allCountries:'Toate țările',loading:'Se încarcă…',catalogOnline:'Catalog online',catalogCache:'Cache local',catalogError:'Catalog indisponibil',catalogCount:'Catalog: {count} posturi',noStations:'Nu s-au găsit posturi',noStationsText:'Schimbă genul sau căutarea și încearcă din nou.',ready:'Gata',chooseStation:'Alege un post de radio',connecting:'Conectare…',playing:'Redare',paused:'Pauză',stopped:'Oprit',streamError:'Fluxul nu poate fi redat',offline:'Offline',online:'Online',sleepTimer:'Temporizator oprire',off:'Oprit',favoriteAdded:'Adăugat la Favorite.',favoriteRemoved:'Eliminat din Favorite.',addToFavorites:'Adaugă la favorite',inFavorites:'În favorite',refresh:'Actualizează',advertising:'Spațiu publicitar',play:'Redă',stop:'Oprește',install:'Instalează'}),
el:full({title:'Διαδικτυακό ραδιόφωνο',local:'Τοπικοί',world:'Κόσμος',favorites:'Αγαπημένα',recent:'Πρόσφατα',country:'Χώρα',currentCountry:'Τρέχουσα χώρα',genre:'Είδος',cancel:'Ακύρωση',save:'Αποθήκευση',search:'Αναζήτηση σταθμών…',localHeading:'Τοπικοί σταθμοί',worldHeading:'Παγκόσμιοι σταθμοί',favoritesHeading:'Αγαπημένοι σταθμοί',recentHeading:'Πρόσφατα ακούσματα',localDesc:'Σταθμοί από την τρέχουσα χώρα: {country}',worldDesc:'Σταθμοί από όλο τον κόσμο',favoritesDesc:'Αγαπημένα αποθηκευμένα τοπικά',recentDesc:'Οι σταθμοί που ακούσατε πρόσφατα',allCountries:'Όλες οι χώρες',loading:'Φόρτωση…',catalogOnline:'Κατάλογος online',catalogCache:'Τοπική cache',catalogError:'Ο κατάλογος δεν είναι διαθέσιμος',catalogCount:'Κατάλογος: {count} σταθμοί',noStations:'Δεν βρέθηκαν σταθμοί',noStationsText:'Αλλάξτε είδος ή αναζήτηση και δοκιμάστε ξανά.',ready:'Έτοιμο',chooseStation:'Επιλέξτε ραδιοφωνικό σταθμό',connecting:'Σύνδεση…',playing:'Αναπαραγωγή',paused:'Παύση',stopped:'Σταμάτησε',streamError:'Η ροή δεν μπορεί να αναπαραχθεί',offline:'Εκτός σύνδεσης',online:'Online',sleepTimer:'Χρονοδιακόπτης ύπνου',off:'Ανενεργό',favoriteAdded:'Προστέθηκε στα Αγαπημένα.',favoriteRemoved:'Αφαιρέθηκε από τα Αγαπημένα.',addToFavorites:'Προσθήκη στα αγαπημένα',inFavorites:'Στα αγαπημένα',refresh:'Ανανέωση',advertising:'Διαφημιστικός χώρος',play:'Αναπαραγωγή',stop:'Διακοπή',install:'Εγκατάσταση'}),
tr:full({title:'Çevrimiçi radyo',local:'Yerel',world:'Dünya',favorites:'Favoriler',recent:'Son dinlenenler',country:'Ülke',currentCountry:'Mevcut ülke',genre:'Tür',cancel:'İptal',save:'Kaydet',search:'İstasyon ara…',localHeading:'Yerel istasyonlar',worldHeading:'Dünya istasyonları',favoritesHeading:'Favori istasyonlar',recentHeading:'Son dinlenenler',localDesc:'Mevcut ülkenizdeki istasyonlar: {country}',worldDesc:'Dünyanın dört bir yanından istasyonlar',favoritesDesc:'Yerel olarak kaydedilen favoriler',recentDesc:'Son dinlediğiniz istasyonlar',allCountries:'Tüm ülkeler',loading:'Yükleniyor…',catalogOnline:'Katalog çevrimiçi',catalogCache:'Yerel önbellek',catalogError:'Katalog kullanılamıyor',catalogCount:'Katalog: {count} istasyon',noStations:'İstasyon bulunamadı',noStationsText:'Türü veya aramayı değiştirip tekrar deneyin.',ready:'Hazır',chooseStation:'Bir radyo istasyonu seçin',connecting:'Bağlanıyor…',playing:'Çalıyor',paused:'Duraklatıldı',stopped:'Durduruldu',streamError:'Yayın oynatılamadı',offline:'Çevrimdışı',online:'Çevrimiçi',sleepTimer:'Uyku zamanlayıcısı',off:'Kapalı',favoriteAdded:'Favorilere eklendi.',favoriteRemoved:'Favorilerden kaldırıldı.',addToFavorites:'Favorilere ekle',inFavorites:'Favorilerde',refresh:'Yenile',advertising:'Reklam alanı',play:'Oynat',stop:'Durdur',install:'Yükle'}),
pl:full({title:'Radio online',local:'Lokalne',world:'Świat',favorites:'Ulubione',recent:'Ostatnio słuchane',country:'Kraj',currentCountry:'Bieżący kraj',genre:'Gatunek',cancel:'Anuluj',save:'Zapisz',search:'Szukaj stacji…',localHeading:'Stacje lokalne',worldHeading:'Stacje światowe',favoritesHeading:'Ulubione stacje',recentHeading:'Ostatnio słuchane',localDesc:'Stacje z bieżącego kraju: {country}',worldDesc:'Stacje z całego świata',favoritesDesc:'Ulubione zapisane lokalnie',recentDesc:'Ostatnio słuchane stacje',allCountries:'Wszystkie kraje',loading:'Ładowanie…',catalogOnline:'Katalog online',catalogCache:'Lokalna pamięć podręczna',catalogError:'Katalog niedostępny',catalogCount:'Katalog: {count} stacji',noStations:'Nie znaleziono stacji',noStationsText:'Zmień gatunek lub wyszukiwanie i spróbuj ponownie.',ready:'Gotowe',chooseStation:'Wybierz stację radiową',connecting:'Łączenie…',playing:'Odtwarzanie',paused:'Pauza',stopped:'Zatrzymano',streamError:'Nie można odtworzyć strumienia',offline:'Offline',online:'Online',sleepTimer:'Wyłącznik czasowy',off:'Wył.',favoriteAdded:'Dodano do Ulubionych.',favoriteRemoved:'Usunięto z Ulubionych.',addToFavorites:'Dodaj do ulubionych',inFavorites:'W ulubionych',refresh:'Odśwież',advertising:'Miejsce na reklamę',play:'Odtwórz',stop:'Zatrzymaj',install:'Zainstaluj'}),
cs:full({title:'Online rádio',local:'Místní',world:'Svět',favorites:'Oblíbené',recent:'Nedávno poslouchané',country:'Země',currentCountry:'Aktuální země',genre:'Žánr',cancel:'Zrušit',save:'Uložit',search:'Hledat stanice…',localHeading:'Místní stanice',worldHeading:'Světové stanice',favoritesHeading:'Oblíbené stanice',recentHeading:'Nedávno poslouchané',localDesc:'Stanice z aktuální země: {country}',worldDesc:'Stanice z celého světa',favoritesDesc:'Oblíbené uložené lokálně',recentDesc:'Naposledy poslouchané stanice',allCountries:'Všechny země',loading:'Načítání…',catalogOnline:'Katalog online',catalogCache:'Lokální cache',catalogError:'Katalog není dostupný',catalogCount:'Katalog: {count} stanic',noStations:'Nebyly nalezeny žádné stanice',noStationsText:'Změňte žánr nebo hledání a zkuste to znovu.',ready:'Připraveno',chooseStation:'Vyberte rozhlasovou stanici',connecting:'Připojování…',playing:'Přehrávání',paused:'Pozastaveno',stopped:'Zastaveno',streamError:'Stream nelze přehrát',offline:'Offline',online:'Online',sleepTimer:'Časovač vypnutí',off:'Vyp.',favoriteAdded:'Přidáno do Oblíbených.',favoriteRemoved:'Odebráno z Oblíbených.',addToFavorites:'Přidat do oblíbených',inFavorites:'V oblíbených',refresh:'Obnovit',advertising:'Reklamní prostor',play:'Přehrát',stop:'Zastavit',install:'Nainstalovat'}),
uk:full({title:'Онлайн-радіо',local:'Місцеві',world:'Світ',favorites:'Улюблені',recent:'Нещодавно слухали',country:'Країна',currentCountry:'Поточна країна',genre:'Жанр',cancel:'Скасувати',save:'Зберегти',search:'Шукати станції…',localHeading:'Місцеві станції',worldHeading:'Світові станції',favoritesHeading:'Улюблені станції',recentHeading:'Нещодавно слухали',localDesc:'Станції з вашої поточної країни: {country}',worldDesc:'Станції з усього світу',favoritesDesc:'Улюблені станції збережені локально',recentDesc:'Ваші нещодавно прослухані станції',allCountries:'Усі країни',loading:'Завантаження…',catalogOnline:'Каталог онлайн',catalogCache:'Локальний кеш',catalogError:'Каталог недоступний',catalogCount:'Каталог: {count} станцій',noStations:'Станцій не знайдено',noStationsText:'Змініть жанр або пошук і спробуйте ще раз.',ready:'Готово',chooseStation:'Виберіть радіостанцію',connecting:'Підключення…',playing:'Відтворюється',paused:'Пауза',stopped:'Зупинено',streamError:'Потік не вдалося відтворити',offline:'Офлайн',online:'Онлайн',sleepTimer:'Таймер сну',off:'Вимк.',favoriteAdded:'Додано до Улюблених.',favoriteRemoved:'Видалено з Улюблених.',addToFavorites:'Додати в улюблені',inFavorites:'В улюблених',refresh:'Оновити',advertising:'Рекламне місце',play:'Відтворити',stop:'Зупинити',install:'Встановити'}),
ru:full({title:'Онлайн-радио',local:'Местные',world:'Мир',favorites:'Избранное',recent:'Недавно слушали',country:'Страна',currentCountry:'Текущая страна',genre:'Жанр',cancel:'Отмена',save:'Сохранить',search:'Поиск станций…',localHeading:'Местные станции',worldHeading:'Станции мира',favoritesHeading:'Избранные станции',recentHeading:'Недавно слушали',localDesc:'Станции из вашей текущей страны: {country}',worldDesc:'Станции со всего мира',favoritesDesc:'Избранное хранится локально',recentDesc:'Недавно прослушанные станции',allCountries:'Все страны',loading:'Загрузка…',catalogOnline:'Каталог онлайн',catalogCache:'Локальный кэш',catalogError:'Каталог недоступен',catalogCount:'Каталог: {count} станций',noStations:'Станции не найдены',noStationsText:'Измените жанр или поиск и попробуйте снова.',ready:'Готово',chooseStation:'Выберите радиостанцию',connecting:'Подключение…',playing:'Воспроизведение',paused:'Пауза',stopped:'Остановлено',streamError:'Поток не удалось воспроизвести',offline:'Офлайн',online:'Онлайн',sleepTimer:'Таймер сна',off:'Выкл.',favoriteAdded:'Добавлено в Избранное.',favoriteRemoved:'Удалено из Избранного.',addToFavorites:'Добавить в избранное',inFavorites:'В избранном',refresh:'Обновить',advertising:'Рекламное место',play:'Воспроизвести',stop:'Остановить',install:'Установить'})
};
const EXTRA_TRANSLATIONS={
en:{remove:'Remove',stationInfo:'Station information',region:'Region',languageLabel:'Language',codec:'Codec',bitrate:'Bitrate',streamType:'Stream type',website:'Website',standardStream:'Standard stream'},
bg:{remove:'Премахни',stationInfo:'Информация за радиостанцията',region:'Регион',languageLabel:'Език',codec:'Кодек',bitrate:'Битрейт',streamType:'Тип поток',website:'Уебсайт',standardStream:'Стандартен поток'},
de:{remove:'Entfernen',stationInfo:'Senderinformationen',region:'Region',languageLabel:'Sprache',codec:'Codec',bitrate:'Bitrate',streamType:'Stream-Typ',website:'Webseite',standardStream:'Standard-Stream'},
fr:{remove:'Supprimer',stationInfo:'Informations sur la station',region:'Région',languageLabel:'Langue',codec:'Codec',bitrate:'Débit',streamType:'Type de flux',website:'Site web',standardStream:'Flux standard'},
es:{remove:'Eliminar',stationInfo:'Información de la emisora',region:'Región',languageLabel:'Idioma',codec:'Códec',bitrate:'Tasa de bits',streamType:'Tipo de flujo',website:'Sitio web',standardStream:'Flujo estándar'},
it:{remove:'Rimuovi',stationInfo:'Informazioni stazione',region:'Regione',languageLabel:'Lingua',codec:'Codec',bitrate:'Bitrate',streamType:'Tipo di stream',website:'Sito web',standardStream:'Stream standard'},
pt:{remove:'Remover',stationInfo:'Informações da estação',region:'Região',languageLabel:'Idioma',codec:'Codec',bitrate:'Taxa de bits',streamType:'Tipo de stream',website:'Site',standardStream:'Stream padrão'},
ro:{remove:'Elimină',stationInfo:'Informații despre post',region:'Regiune',languageLabel:'Limbă',codec:'Codec',bitrate:'Bitrate',streamType:'Tip flux',website:'Site web',standardStream:'Flux standard'},
el:{remove:'Αφαίρεση',stationInfo:'Πληροφορίες σταθμού',region:'Περιοχή',languageLabel:'Γλώσσα',codec:'Codec',bitrate:'Bitrate',streamType:'Τύπος ροής',website:'Ιστότοπος',standardStream:'Τυπική ροή'},
tr:{remove:'Kaldır',stationInfo:'İstasyon bilgileri',region:'Bölge',languageLabel:'Dil',codec:'Codec',bitrate:'Bit hızı',streamType:'Yayın türü',website:'Web sitesi',standardStream:'Standart yayın'},
pl:{remove:'Usuń',stationInfo:'Informacje o stacji',region:'Region',languageLabel:'Język',codec:'Kodek',bitrate:'Przepływność',streamType:'Typ strumienia',website:'Strona WWW',standardStream:'Standardowy strumień'},
cs:{remove:'Odebrat',stationInfo:'Informace o stanici',region:'Region',languageLabel:'Jazyk',codec:'Kodek',bitrate:'Datový tok',streamType:'Typ streamu',website:'Web',standardStream:'Standardní stream'},
uk:{remove:'Видалити',stationInfo:'Інформація про радіостанцію',region:'Регіон',languageLabel:'Мова',codec:'Кодек',bitrate:'Бітрейт',streamType:'Тип потоку',website:'Вебсайт',standardStream:'Стандартний потік'},
ru:{remove:'Удалить',stationInfo:'Информация о радиостанции',region:'Регион',languageLabel:'Язык',codec:'Кодек',bitrate:'Битрейт',streamType:'Тип потока',website:'Сайт',standardStream:'Стандартный поток'}
};
for(const [code,values] of Object.entries(EXTRA_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
const BETA6_TRANSLATIONS={
en:{appearance:'Visual style',about:'About',appearanceDesc:'Choose a ready-made color style. Text colors adapt for clear readability.',themeNeon:'Neon Night',themeAurora:'Aurora',themeSunset:'Sunset',themeEmerald:'Emerald',themeArctic:'Arctic Light',themeGraphite:'Graphite Gold',themeDarkReadable:'Dark background · light text',themeLightReadable:'Light background · dark text',aboutDesc:'Product, version and service information.',developer:'Developed by',createdOn:'Created on',version:'Version',appLicense:'License',allRightsReserved:'All rights reserved',catalogService:'Radio catalog',storage:'Storage',localStorageInfo:'Local on the device',aboutNetworkNote:'An internet connection is required for the catalog and playback of internet radio stations.',aboutThirdPartyNote:'Radio Browser is an external service and is not part of SSGPT14 Radio. External streams and services are subject to their respective providers terms.',resultsCount:'Results: {count} stations'},
bg:{appearance:'Стил на визуализация',about:'За приложението',appearanceDesc:'Избери готов цветови стил. Цветът на текста се настройва за добра четимост.',themeNeon:'Neon Night',themeAurora:'Aurora',themeSunset:'Sunset',themeEmerald:'Emerald',themeArctic:'Arctic Light',themeGraphite:'Graphite Gold',themeDarkReadable:'Тъмен фон · светъл текст',themeLightReadable:'Светъл фон · тъмен текст',aboutDesc:'Информация за продукта, версията и използваните услуги.',developer:'Разработил',createdOn:'Дата на създаване',version:'Версия',appLicense:'Лиценз',allRightsReserved:'Всички права запазени',catalogService:'Радио каталог',storage:'Съхранение',localStorageInfo:'Локално на устройството',aboutNetworkNote:'За каталога и възпроизвеждането на интернет радиостанции е необходима интернет връзка.',aboutThirdPartyNote:'Radio Browser е външна услуга и не е част от SSGPT14 Radio. Условията на външните потоци и услуги се определят от съответните им доставчици.',resultsCount:'Резултати: {count} радиостанции'},
de:{appearance:'Darstellungsstil',about:'Über die App',appearanceDesc:'Wähle einen fertigen Farbstil. Die Textfarbe wird für gute Lesbarkeit angepasst.',developer:'Entwickelt von',createdOn:'Erstellt am',version:'Version',appLicense:'Lizenz',allRightsReserved:'Alle Rechte vorbehalten',catalogService:'Radiokatalog',storage:'Speicher',localStorageInfo:'Lokal auf dem Gerät',resultsCount:'Ergebnisse: {count} Sender'},
fr:{appearance:'Style visuel',about:'À propos',appearanceDesc:'Choisissez un style de couleurs prédéfini. La couleur du texte s’adapte pour rester lisible.',developer:'Développé par',createdOn:'Créé le',version:'Version',appLicense:'Licence',allRightsReserved:'Tous droits réservés',catalogService:'Catalogue radio',storage:'Stockage',localStorageInfo:'Local sur l’appareil',resultsCount:'Résultats : {count} stations'},
es:{appearance:'Estilo visual',about:'Acerca de',appearanceDesc:'Elige un estilo de color predefinido. El color del texto se adapta para mantener la legibilidad.',developer:'Desarrollado por',createdOn:'Fecha de creación',version:'Versión',appLicense:'Licencia',allRightsReserved:'Todos los derechos reservados',catalogService:'Catálogo de radio',storage:'Almacenamiento',localStorageInfo:'Local en el dispositivo',resultsCount:'Resultados: {count} emisoras'},
it:{appearance:'Stile visivo',about:'Informazioni',appearanceDesc:'Scegli uno stile colore pronto. Il colore del testo si adatta per restare leggibile.',developer:'Sviluppato da',createdOn:'Data di creazione',version:'Versione',appLicense:'Licenza',allRightsReserved:'Tutti i diritti riservati',catalogService:'Catalogo radio',storage:'Archiviazione',localStorageInfo:'Locale sul dispositivo',resultsCount:'Risultati: {count} stazioni'},
pt:{appearance:'Estilo visual',about:'Sobre',appearanceDesc:'Escolha um estilo de cores pronto. A cor do texto ajusta-se para manter boa legibilidade.',developer:'Desenvolvido por',createdOn:'Data de criação',version:'Versão',appLicense:'Licença',allRightsReserved:'Todos os direitos reservados',catalogService:'Catálogo de rádio',storage:'Armazenamento',localStorageInfo:'Local no dispositivo',resultsCount:'Resultados: {count} estações'},
ro:{appearance:'Stil vizual',about:'Despre aplicație',appearanceDesc:'Alege un stil de culoare pregătit. Culoarea textului se adaptează pentru lizibilitate.',developer:'Dezvoltat de',createdOn:'Data creării',version:'Versiune',appLicense:'Licență',allRightsReserved:'Toate drepturile rezervate',catalogService:'Catalog radio',storage:'Stocare',localStorageInfo:'Local pe dispozitiv',resultsCount:'Rezultate: {count} posturi'},
el:{appearance:'Στυλ εμφάνισης',about:'Σχετικά',appearanceDesc:'Επιλέξτε έτοιμο χρωματικό στυλ. Το χρώμα κειμένου προσαρμόζεται για ευκρίνεια.',developer:'Ανάπτυξη από',createdOn:'Ημερομηνία δημιουργίας',version:'Έκδοση',appLicense:'Άδεια',allRightsReserved:'Με επιφύλαξη παντός δικαιώματος',catalogService:'Κατάλογος ραδιοφώνων',storage:'Αποθήκευση',localStorageInfo:'Τοπικά στη συσκευή',resultsCount:'Αποτελέσματα: {count} σταθμοί'},
tr:{appearance:'Görünüm stili',about:'Uygulama hakkında',appearanceDesc:'Hazır bir renk stili seçin. Metin rengi okunabilirlik için uyarlanır.',developer:'Geliştiren',createdOn:'Oluşturulma tarihi',version:'Sürüm',appLicense:'Lisans',allRightsReserved:'Tüm hakları saklıdır',catalogService:'Radyo kataloğu',storage:'Depolama',localStorageInfo:'Cihazda yerel',resultsCount:'Sonuçlar: {count} istasyon'},
pl:{appearance:'Styl wyglądu',about:'O aplikacji',appearanceDesc:'Wybierz gotowy styl kolorów. Kolor tekstu dopasowuje się dla czytelności.',developer:'Opracował',createdOn:'Data utworzenia',version:'Wersja',appLicense:'Licencja',allRightsReserved:'Wszelkie prawa zastrzeżone',catalogService:'Katalog radia',storage:'Pamięć',localStorageInfo:'Lokalnie na urządzeniu',resultsCount:'Wyniki: {count} stacji'},
cs:{appearance:'Vzhled',about:'O aplikaci',appearanceDesc:'Vyberte připravený barevný styl. Barva textu se přizpůsobí pro dobrou čitelnost.',developer:'Vyvinul',createdOn:'Datum vytvoření',version:'Verze',appLicense:'Licence',allRightsReserved:'Všechna práva vyhrazena',catalogService:'Rádiový katalog',storage:'Úložiště',localStorageInfo:'Lokálně v zařízení',resultsCount:'Výsledky: {count} stanic'},
uk:{appearance:'Стиль оформлення',about:'Про застосунок',appearanceDesc:'Оберіть готовий кольоровий стиль. Колір тексту адаптується для читабельності.',developer:'Розробив',createdOn:'Дата створення',version:'Версія',appLicense:'Ліцензія',allRightsReserved:'Усі права захищено',catalogService:'Каталог радіо',storage:'Зберігання',localStorageInfo:'Локально на пристрої',resultsCount:'Результати: {count} станцій'},
ru:{appearance:'Стиль оформления',about:'О приложении',appearanceDesc:'Выберите готовый цветовой стиль. Цвет текста адаптируется для читаемости.',developer:'Разработал',createdOn:'Дата создания',version:'Версия',appLicense:'Лицензия',allRightsReserved:'Все права защищены',catalogService:'Каталог радио',storage:'Хранение',localStorageInfo:'Локально на устройстве',resultsCount:'Результаты: {count} станций'}
};
for(const [code,values] of Object.entries(BETA6_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
const BETA10_TRANSLATIONS={
de:{catalogLoadingText:'Verbindung zum Radiokatalog wird hergestellt…'},
fr:{catalogLoadingText:'Connexion au catalogue radio…'},
es:{catalogLoadingText:'Conectando con el catálogo de radio…'},
it:{catalogLoadingText:'Connessione al catalogo radio…'},
pt:{catalogLoadingText:'A ligar ao catálogo de rádio…'},
ro:{catalogLoadingText:'Conectare la catalogul radio…'},
el:{catalogLoadingText:'Σύνδεση με τον κατάλογο ραδιοφώνων…'},
tr:{catalogLoadingText:'Radyo kataloğuna bağlanılıyor…'},
pl:{catalogLoadingText:'Łączenie z katalogiem radia…'},
cs:{catalogLoadingText:'Připojování k rádiovému katalogu…'},
uk:{catalogLoadingText:'Підключення до каталогу радіо…'},
ru:{catalogLoadingText:'Подключение к каталогу радио…'}
};
for(const [code,values] of Object.entries(BETA10_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
const BETA14_MONETIZATION_TRANSLATIONS={
de:{privacySettings:'Datenschutzeinstellungen',testAdsBadge:'TESTANZEIGEN · keine echten Einnahmen',webConsentTestNote:'Dies ist eine Test-Einwilligungsoberfläche für die Entwicklung. Ein produktiver Web-CMP ist noch nicht konfiguriert.',allowTestAds:'Testanzeigen erlauben',limitTestAds:'Testanzeigen einschränken',close:'Schließen'},
fr:{privacySettings:'Paramètres de confidentialité',testAdsBadge:'ANNONCES TEST · aucun revenu réel',webConsentTestNote:'Ceci est une interface de consentement de test pour le développement. Aucun CMP Web de production n’est encore configuré.',allowTestAds:'Autoriser les annonces test',limitTestAds:'Limiter les annonces test',close:'Fermer'},
es:{privacySettings:'Ajustes de privacidad',testAdsBadge:'ANUNCIOS DE PRUEBA · sin ingresos reales',webConsentTestNote:'Esta es una interfaz de consentimiento de prueba para desarrollo. Aún no hay un CMP Web de producción configurado.',allowTestAds:'Permitir anuncios de prueba',limitTestAds:'Limitar anuncios de prueba',close:'Cerrar'},
it:{privacySettings:'Impostazioni privacy',testAdsBadge:'ANNUNCI DI TEST · nessun ricavo reale',webConsentTestNote:'Questa è un’interfaccia di consenso di test per lo sviluppo. Un CMP Web di produzione non è ancora configurato.',allowTestAds:'Consenti annunci di test',limitTestAds:'Limita annunci di test',close:'Chiudi'},
pt:{privacySettings:'Definições de privacidade',testAdsBadge:'ANÚNCIOS DE TESTE · sem receita real',webConsentTestNote:'Esta é uma interface de consentimento de teste para desenvolvimento. Ainda não está configurado um CMP Web de produção.',allowTestAds:'Permitir anúncios de teste',limitTestAds:'Limitar anúncios de teste',close:'Fechar'},
ro:{privacySettings:'Setări de confidențialitate',testAdsBadge:'RECLAME DE TEST · fără venit real',webConsentTestNote:'Aceasta este o interfață de consimțământ de test pentru dezvoltare. Un CMP Web de producție nu este încă configurat.',allowTestAds:'Permite reclame de test',limitTestAds:'Limitează reclamele de test',close:'Închide'},
el:{privacySettings:'Ρυθμίσεις απορρήτου',testAdsBadge:'ΔΟΚΙΜΑΣΤΙΚΕΣ ΔΙΑΦΗΜΙΣΕΙΣ · χωρίς πραγματικά έσοδα',webConsentTestNote:'Αυτή είναι δοκιμαστική διεπαφή συγκατάθεσης για ανάπτυξη. Δεν έχει ακόμη ρυθμιστεί Web CMP παραγωγής.',allowTestAds:'Να επιτρέπονται δοκιμαστικές διαφημίσεις',limitTestAds:'Περιορισμός δοκιμαστικών διαφημίσεων',close:'Κλείσιμο'},
tr:{privacySettings:'Gizlilik ayarları',testAdsBadge:'TEST REKLAMLARI · gerçek gelir yok',webConsentTestNote:'Bu, geliştirme için test izin arayüzüdür. Üretim Web CMP henüz yapılandırılmadı.',allowTestAds:'Test reklamlarına izin ver',limitTestAds:'Test reklamlarını sınırla',close:'Kapat'},
pl:{privacySettings:'Ustawienia prywatności',testAdsBadge:'REKLAMY TESTOWE · bez realnych przychodów',webConsentTestNote:'To jest testowy interfejs zgody do celów deweloperskich. Produkcyjny Web CMP nie jest jeszcze skonfigurowany.',allowTestAds:'Zezwól na reklamy testowe',limitTestAds:'Ogranicz reklamy testowe',close:'Zamknij'},
cs:{privacySettings:'Nastavení soukromí',testAdsBadge:'TESTOVACÍ REKLAMY · bez skutečných příjmů',webConsentTestNote:'Toto je testovací rozhraní souhlasu pro vývoj. Produkční Web CMP zatím není nakonfigurován.',allowTestAds:'Povolit testovací reklamy',limitTestAds:'Omezit testovací reklamy',close:'Zavřít'},
uk:{privacySettings:'Налаштування конфіденційності',testAdsBadge:'ТЕСТОВА РЕКЛАМА · без реального доходу',webConsentTestNote:'Це тестовий інтерфейс згоди для розробки. Production Web CMP ще не налаштовано.',allowTestAds:'Дозволити тестову рекламу',limitTestAds:'Обмежити тестову рекламу',close:'Закрити'},
ru:{privacySettings:'Настройки конфиденциальности',testAdsBadge:'ТЕСТОВАЯ РЕКЛАМА · без реального дохода',webConsentTestNote:'Это тестовый интерфейс согласия для разработки. Production Web CMP ещё не настроен.',allowTestAds:'Разрешить тестовую рекламу',limitTestAds:'Ограничить тестовую рекламу',close:'Закрыть'}
};
for(const [code,values] of Object.entries(BETA14_MONETIZATION_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
const BETA13_TRANSLATIONS={
en:{storageError:'Local changes could not be saved. Check available device storage.'},
bg:{storageError:'Локалните промени не могат да бъдат запазени. Провери свободното място на устройството.'},
de:{storageError:'Lokale Änderungen konnten nicht gespeichert werden. Prüfe den verfügbaren Gerätespeicher.'},
fr:{storageError:'Les modifications locales n’ont pas pu être enregistrées. Vérifiez l’espace disponible sur l’appareil.'},
es:{storageError:'No se pudieron guardar los cambios locales. Comprueba el espacio disponible del dispositivo.'},
it:{storageError:'Impossibile salvare le modifiche locali. Controlla lo spazio disponibile sul dispositivo.'},
pt:{storageError:'Não foi possível guardar as alterações locais. Verifique o espaço disponível no dispositivo.'},
ro:{storageError:'Modificările locale nu au putut fi salvate. Verifică spațiul disponibil pe dispozitiv.'},
el:{storageError:'Δεν ήταν δυνατή η αποθήκευση των τοπικών αλλαγών. Ελέγξτε τον διαθέσιμο χώρο της συσκευής.'},
tr:{storageError:'Yerel değişiklikler kaydedilemedi. Cihazdaki kullanılabilir alanı kontrol edin.'},
pl:{storageError:'Nie udało się zapisać lokalnych zmian. Sprawdź wolne miejsce na urządzeniu.'},
cs:{storageError:'Místní změny se nepodařilo uložit. Zkontrolujte volné místo v zařízení.'},
uk:{storageError:'Не вдалося зберегти локальні зміни. Перевірте вільне місце на пристрої.'},
ru:{storageError:'Не удалось сохранить локальные изменения. Проверьте свободное место на устройстве.'}
};
for(const [code,values] of Object.entries(BETA13_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
const RIGHTS_GATE_TRANSLATIONS={
en:{rightsStatusLabel:'Embedding rights',rightsEmbedOk:'Embedding allowed',rightsLinkOnly:'Official site only',rightsBlocked:'Blocked',rightsReview:'Rights review required',rightsOpenOfficial:'Open official site',rightsPlaybackDenied:'In-app playback is unavailable until embedding and commercial-use rights are verified.',aboutRightsNote:'The built-in player accepts only stations with verified permission for embedding and commercial use. Without evidence, the app offers the official site only or marks the station for review.'},
bg:{rightsStatusLabel:'Права за вграждане',rightsEmbedOk:'Вграждането е разрешено',rightsLinkOnly:'Само официален сайт',rightsBlocked:'Блокирано',rightsReview:'Нужна е проверка на правата',rightsOpenOfficial:'Отвори официалния сайт',rightsPlaybackDenied:'Възпроизвеждането в приложението е недостъпно, докато не се потвърдят правата за вграждане и търговска употреба.',aboutRightsNote:'Вграденият Player допуска само станции с проверено разрешение за вграждане и търговска употреба. При липса на доказателство приложението предлага само официалния сайт или маркира станцията за преглед.'},
de:{rightsStatusLabel:'Einbettungsrechte',rightsEmbedOk:'Einbettung erlaubt',rightsLinkOnly:'Nur offizielle Website',rightsBlocked:'Gesperrt',rightsReview:'Rechteprüfung erforderlich',rightsOpenOfficial:'Offizielle Website öffnen',rightsPlaybackDenied:'Die Wiedergabe in der App ist erst nach Prüfung der Einbettungs- und kommerziellen Nutzungsrechte verfügbar.',aboutRightsNote:'Der integrierte Player akzeptiert nur Sender mit verifizierter Erlaubnis zur Einbettung und kommerziellen Nutzung. Ohne Nachweis wird nur die offizielle Website angeboten oder der Sender zur Prüfung markiert.'},
fr:{rightsStatusLabel:"Droits d’intégration",rightsEmbedOk:'Intégration autorisée',rightsLinkOnly:'Site officiel uniquement',rightsBlocked:'Bloquée',rightsReview:'Vérification des droits requise',rightsOpenOfficial:'Ouvrir le site officiel',rightsPlaybackDenied:"La lecture dans l’application est indisponible tant que les droits d’intégration et d’usage commercial ne sont pas vérifiés.",aboutRightsNote:"Le lecteur intégré n’accepte que les stations disposant d’une autorisation vérifiée pour l’intégration et l’usage commercial. Sans preuve, l’application propose uniquement le site officiel ou marque la station pour examen."},
es:{rightsStatusLabel:'Derechos de inserción',rightsEmbedOk:'Inserción permitida',rightsLinkOnly:'Solo sitio oficial',rightsBlocked:'Bloqueada',rightsReview:'Se requiere revisar los derechos',rightsOpenOfficial:'Abrir sitio oficial',rightsPlaybackDenied:'La reproducción en la aplicación no está disponible hasta verificar los derechos de inserción y uso comercial.',aboutRightsNote:'El reproductor integrado solo acepta emisoras con permiso verificado para inserción y uso comercial. Sin pruebas, la aplicación ofrece solo el sitio oficial o marca la emisora para revisión.'},
it:{rightsStatusLabel:'Diritti di incorporamento',rightsEmbedOk:'Incorporamento consentito',rightsLinkOnly:'Solo sito ufficiale',rightsBlocked:'Bloccata',rightsReview:'Verifica dei diritti necessaria',rightsOpenOfficial:'Apri sito ufficiale',rightsPlaybackDenied:'La riproduzione nell’app non è disponibile finché non sono verificati i diritti di incorporamento e uso commerciale.',aboutRightsNote:'Il player integrato accetta solo stazioni con autorizzazione verificata per incorporamento e uso commerciale. Senza prova, l’app offre solo il sito ufficiale o contrassegna la stazione per revisione.'},
pt:{rightsStatusLabel:'Direitos de incorporação',rightsEmbedOk:'Incorporação permitida',rightsLinkOnly:'Apenas site oficial',rightsBlocked:'Bloqueada',rightsReview:'Revisão de direitos necessária',rightsOpenOfficial:'Abrir site oficial',rightsPlaybackDenied:'A reprodução na aplicação fica indisponível até serem verificados os direitos de incorporação e uso comercial.',aboutRightsNote:'O leitor integrado aceita apenas estações com permissão verificada para incorporação e uso comercial. Sem prova, a aplicação oferece apenas o site oficial ou marca a estação para revisão.'},
ro:{rightsStatusLabel:'Drepturi de încorporare',rightsEmbedOk:'Încorporare permisă',rightsLinkOnly:'Doar site oficial',rightsBlocked:'Blocat',rightsReview:'Este necesară verificarea drepturilor',rightsOpenOfficial:'Deschide site-ul oficial',rightsPlaybackDenied:'Redarea în aplicație nu este disponibilă până la verificarea drepturilor de încorporare și utilizare comercială.',aboutRightsNote:'Playerul integrat acceptă numai posturi cu permisiune verificată pentru încorporare și utilizare comercială. Fără dovezi, aplicația oferă doar site-ul oficial sau marchează postul pentru verificare.'},
el:{rightsStatusLabel:'Δικαιώματα ενσωμάτωσης',rightsEmbedOk:'Η ενσωμάτωση επιτρέπεται',rightsLinkOnly:'Μόνο επίσημος ιστότοπος',rightsBlocked:'Αποκλεισμένο',rightsReview:'Απαιτείται έλεγχος δικαιωμάτων',rightsOpenOfficial:'Άνοιγμα επίσημου ιστοτόπου',rightsPlaybackDenied:'Η αναπαραγωγή στην εφαρμογή δεν είναι διαθέσιμη μέχρι να επαληθευτούν τα δικαιώματα ενσωμάτωσης και εμπορικής χρήσης.',aboutRightsNote:'Ο ενσωματωμένος player δέχεται μόνο σταθμούς με επαληθευμένη άδεια για ενσωμάτωση και εμπορική χρήση. Χωρίς αποδεικτικά, η εφαρμογή προσφέρει μόνο τον επίσημο ιστότοπο ή σημειώνει τον σταθμό για έλεγχο.'},
tr:{rightsStatusLabel:'Gömme hakları',rightsEmbedOk:'Gömme izinli',rightsLinkOnly:'Yalnızca resmi site',rightsBlocked:'Engellendi',rightsReview:'Hak incelemesi gerekli',rightsOpenOfficial:'Resmi siteyi aç',rightsPlaybackDenied:'Gömme ve ticari kullanım hakları doğrulanana kadar uygulama içi oynatma kullanılamaz.',aboutRightsNote:'Yerleşik oynatıcı yalnızca gömme ve ticari kullanım izni doğrulanmış istasyonları kabul eder. Kanıt yoksa uygulama yalnızca resmi siteyi sunar veya istasyonu inceleme için işaretler.'},
pl:{rightsStatusLabel:'Prawa do osadzania',rightsEmbedOk:'Osadzanie dozwolone',rightsLinkOnly:'Tylko oficjalna strona',rightsBlocked:'Zablokowana',rightsReview:'Wymagana weryfikacja praw',rightsOpenOfficial:'Otwórz oficjalną stronę',rightsPlaybackDenied:'Odtwarzanie w aplikacji jest niedostępne do czasu potwierdzenia praw do osadzania i użytku komercyjnego.',aboutRightsNote:'Wbudowany odtwarzacz przyjmuje tylko stacje z potwierdzonym zezwoleniem na osadzanie i użytek komercyjny. Bez dowodu aplikacja oferuje tylko oficjalną stronę lub oznacza stację do weryfikacji.'},
cs:{rightsStatusLabel:'Práva k vložení',rightsEmbedOk:'Vložení povoleno',rightsLinkOnly:'Pouze oficiální web',rightsBlocked:'Blokováno',rightsReview:'Je nutná kontrola práv',rightsOpenOfficial:'Otevřít oficiální web',rightsPlaybackDenied:'Přehrávání v aplikaci není dostupné, dokud nejsou ověřena práva k vložení a komerčnímu užití.',aboutRightsNote:'Vestavěný přehrávač přijímá pouze stanice s ověřeným povolením k vložení a komerčnímu užití. Bez důkazu aplikace nabízí jen oficiální web nebo označí stanici ke kontrole.'},
uk:{rightsStatusLabel:'Права на вбудовування',rightsEmbedOk:'Вбудовування дозволено',rightsLinkOnly:'Лише офіційний сайт',rightsBlocked:'Заблоковано',rightsReview:'Потрібна перевірка прав',rightsOpenOfficial:'Відкрити офіційний сайт',rightsPlaybackDenied:'Відтворення в застосунку недоступне, доки не підтверджено права на вбудовування та комерційне використання.',aboutRightsNote:'Вбудований програвач приймає лише станції з перевіреним дозволом на вбудовування та комерційне використання. Без доказу застосунок пропонує лише офіційний сайт або позначає станцію для перевірки.'},
ru:{rightsStatusLabel:'Права на встраивание',rightsEmbedOk:'Встраивание разрешено',rightsLinkOnly:'Только официальный сайт',rightsBlocked:'Заблокировано',rightsReview:'Требуется проверка прав',rightsOpenOfficial:'Открыть официальный сайт',rightsPlaybackDenied:'Воспроизведение в приложении недоступно, пока не подтверждены права на встраивание и коммерческое использование.',aboutRightsNote:'Встроенный плеер принимает только станции с подтверждённым разрешением на встраивание и коммерческое использование. Без доказательства приложение предлагает только официальный сайт или помечает станцию для проверки.'}
};
for(const [code,values] of Object.entries(RIGHTS_GATE_TRANSLATIONS))Object.assign(TRANSLATIONS[code],values);
export const SUPPORTED_LANGUAGE_CODES=LANGUAGES.map(([code])=>code);
export function normalizeLanguage(value,fallback='en'){
const raw=String(value||'').trim().toLowerCase().replace('_','-');
const base=raw.split('-')[0];
return SUPPORTED_LANGUAGE_CODES.includes(base)?base:fallback;
}
export function translate(language,key,vars={}){
const lang=normalizeLanguage(language,'en');
let text=TRANSLATIONS[lang]?.[key]??EN[key]??key;
for(const [name,value] of Object.entries(vars))text=text.replaceAll(`{${name}}`,String(value));
return text;
}
